public class dataTypes {
	 public static void addNumbers(){
        Integer a = 2;
        Integer b = 3;
        String c = 'word';
        Boolean d = true;
        Boolean e = false;
        Date t = Date.today();
        Datetime n = System.now();
      
    }
    public static void newCon(){
        Contact  x = new Contact();
        x.FirstName = 'Owais';
        x.LastName = 'Ahmed';
        x.Phone = '9302154687';
        x.Email = 'owais910@gmail.com';
        insert x;
        
    }
}